name: Build Xash3D WASM

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.66

      - name: Build engine with emmake
        run: |
          cd xash3d-fwgs/engine
          emmake make -j4
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xash3d-wasm-build
          path: xash3d-fwgs/engine/bin
