name: Build Xash3D Engine for WebAssembly

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.66

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip

      - name: Build engine with waf
        run: |
          cd xash3d-fwgs
          ./waf configure --emscripten
          ./waf build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xash3d-wasm-build
          path: xash3d-fwgs/build/emscripten
